repos:
    - repo: local
      hooks:
          - id: autoflake
            name: autoflake
            entry: poetry run autoflake --in-place --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports -r app/
            language: system
            always_run: true
            pass_filenames: false
          - id: black
            name: black
            entry: poetry run black app/
            language: system
            always_run: true
            pass_filenames: false
